# Generated by Django 6.0.6 on 2026-06-18 10:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claim', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GatewayConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('api_endpoint', models.URLField(blank=True, default='')),
                ('api_key', models.TextField(blank=True, default='')),
                ('secret_key', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Gateway Configuration',
                'verbose_name_plural': 'Gateway Configurations',
            },
        ),
        migrations.CreateModel(
            name='SOSYSLegacyLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_code', models.CharField(max_length=50)),
                ('health_facility', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.CharField(blank=True, default='', max_length=50)),
                ('sosys_status', models.CharField(blank=True, default='', max_length=50)),
                ('match_status', models.CharField(choices=[('MATCHED', 'Matched'), ('UNMATCHED', 'Unmatched'), ('FLAGGED', 'Flagged')], default='UNMATCHED', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('resolved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'SOSYS Legacy Log',
                'verbose_name_plural': 'SOSYS Legacy Logs',
            },
        ),
        migrations.CreateModel(
            name='PaymentBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('claim_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('EXECUTING', 'Executing'), ('DONE', 'Done'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], default='QUEUED', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samanvaya_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Batch',
                'verbose_name_plural': 'Payment Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='QUEUED', max_length=20)),
                ('gateway_name', models.CharField(default='mock_bank', max_length=50)),
                ('gateway_ref_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('raw_request_log', models.JSONField(blank=True, null=True)),
                ('raw_response_log', models.JSONField(blank=True, null=True)),
                ('webhook_received_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='samanvaya.paymentbatch')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samanvaya_transactions', to='claim.claim')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
