# Generated by Django 6.0.6 on 2026-06-18 10:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthFacility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('district', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('insuree_name', models.CharField(blank=True, default='', max_length=200)),
                ('claimed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('approved', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.IntegerField(choices=[(1, 'Rejected'), (2, 'Entered'), (4, 'Checked/Approved'), (8, 'Processed'), (16, 'Valuated')], default=2)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('health_facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='claim.healthfacility')),
            ],
        ),
    ]
